### ISSUE TITLE
clearInterval() is called two times in close() method

### ISSUE THREAD

**Issue by vlakoff** [ChlodAlejandro/wikimedia-streams#3]
See the current `close()` function:
https://github.com/ChlodAlejandro/wikimedia-streams/blob/ef1fb926b5007618277bb18567753568c874e939/src/index.ts#L293-L304

I think that's because the "missing clearInterval()" issue has been fixed two times separately:
* https://github.com/ChlodAlejandro/wikimedia-streams/commit/90635194b72af661026ab36f41b0ea6b93a19b9f
* https://github.com/ChlodAlejandro/wikimedia-streams/pull/2/commits/2deed3a279ef8076b803fe55799ea43bd69a3820

but the former had been't pushed at the time, so the latter didn't see it.

**Comment by ChlodAlejandro** [comment]
You're right about that guess. Seems like I didn't pick up on that during the merge. I'll have it fixed in a bit (and also implement your suggestions on #2) along with some maintenance changes.

**Comment by ChlodAlejandro** [comment]
Fixed, will be deployed in next version.

**Comment by vlakoff** [comment]
Just to clarify, the fix has been't made in 344e08bac7b477576a2745afb6e65806492dd98d but in the previous commit [`7cd0569`#L302](https://github.com/ChlodAlejandro/wikimedia-streams/commit/7cd0569092a88dfd06e9a39fb77f14ee4b1a8a19#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L302).
