### ISSUE TITLE
Document ways to filter stream

### ISSUE THREAD

**Issue by karolinkas** [ChlodAlejandro/wikimedia-streams#5]
Hey Chlod,

I very much enjoy your library. I am curious to learn how I could filter a stream for server_name, wiki, type, or title. When getting recent changes the stream is giant and I wonder if there's a way to filter in advance rather than conditionally looking at the events I need. I would be happy to document it once I understand.

All the best,
Karolin

**Comment by ChlodAlejandro** [comment]
Hello, Karolin!

Unfortunately, Wikimedia's EventStreams doesn't provide an option to filter on the server side (see [wikitech:Event Platform/EventStreams#Filtering](https://wikitech.wikimedia.org/wiki/Event_Platform/EventStreams#Filtering)). The only way to filter the results is on the client side (the application that would depend on this library).

I could add options on the library side but that wouldn't decrease the amount of bandwidth used and I'm afraid this would just lead a bit of overscope (considering this wouldn't be more than a couple lines in someone else's implementation).

**Comment by ChlodAlejandro** [comment]
Hi, @karolinkas! Sorry for the late resolution. I've released the `1.0.0-rc0` release candidate; please check it out and feel free to give feedback! Usage instructions for filters can be found on the README.

I'll be closing this issue now, but do make a comment if you feel that something needs improvement or fixing. Thank you!
